mysite/events/urls.py
from django.urls import path
from events.views.events import create_event, edit_event, table_event
from events.views.participants import (add_participant, edit_participant, table_participant,
                                        user_participant_table, withdraw_table)
from events.views.deleted_events import delete_event, return_deleted, table_deleted 
from events.views.auto_join import join_specific_event, withdraw_specific_event
from events.views.search import search_event_date

from events.views.home import user_expire_events

app_name = 'events'
urlpatterns = [
    # for event add, edit 
    path('create/event/', create_event, name='create_event'),
    path('edit/event/<int:id>/', edit_event, name='edit_event'),

    # deleted and return deleted
    path('delete/event/<int:id>/', delete_event, name='delete_event'),
    path('return/deleted/event/<int:id>/', return_deleted, name='return_deleted'),
    path('all/deleted/event/for/user/<int:user>/', table_deleted, name='table_deleted'),

    # table create event for a user
    path('all/created/events/for/user/<int:user>/', table_event, name='table_event'),
    
    # for participants add, edit
    path('add/participant/', add_participant, name='add_participant'),
    path('edit/participant/<int:id>/', edit_participant, name='edit_participant'),
    
    # table participants  
    path('all/attended/events/for/all/users/', table_participant, name='table_participant'),
    path('all/attended/events/for/user/<int:user>/', user_participant_table, name="user_participant_table"),
    path('all/withdraw/events/for/user/<int:user>/', withdraw_table, name='withdraw_table'),
    
    # table expire for a user  
    path('all/expire/events/for/user/<int:user>/', user_expire_events, name='user_expire_events'),

    # join.py
    path('join/specific/event/<int:event_id>/<int:user>/', join_specific_event, name='join_specific_event'),
    path('withdraw/specific/event/<int:event_id>/<int:user>/', withdraw_specific_event, name='withdraw_specific_event'),

    # search.py
    path('search/date/from/to', search_event_date, name='search_event_date'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views

from events.views.home import frontpage, dashboard, list_active_events, list_expire_events
# from accounts.views import signup, register_page, login_page

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # for home.py
    path('', frontpage, name='frontpage'),
    path('dashboard/', dashboard, name='dashboard'),
    path('list/all/active/events/', list_active_events, name='list_active_events'),
    path('list/all/expire/events/', list_expire_events, name='list_expire_events'),
    
    # events App.
    path('events/', include('events.urls', namespace='events')),
    
    # authentication App.
    path('accounts/', include('allauth.urls')),
    
    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

    # path('signup/', register_page, name='signup'),
    # path('login/', login_page, name='login'),
    
    # path('login/', views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
        <title>Events Application</title>

        <!--  -->
        {% include "base/css.html" %}
        <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
    </head>
    <body>

        <!--  -->
        {% include "base/navbar.html" with brand_name=Events %}
        
        <div class="container">
            <!--  -->       
            {% include "base/search_bar.html" %}
            
            <!--  -->
            {% include "base/messages.html" %}
            

            {% block content %}
            {% endblock %}
            
        </div>

        {% include "home/pagination.html" with page=event_page %}
        <br>
        <br>
        <br>

        <!-- <footer class="footer" id="footer-vue">
            <div class="content has-text-centered">
                <img :src="image"> <p><strong>Events Project</strong> [ msg ]</p> 
            </div>
        </footer> -->
        <nav class="navbar fixed-bottom navbar-dark bg-dark" id="footer-vue">
            <a class="navbar-brand" href="#">&copy; Amr Aly {% now ' Y' %}</a>
            <div class="navbar-brand">
                <!-- <img :src="image"> <p><strong>Events Project</strong> [ msg ]</p>  -->
            </div>
        </nav>

        <!--  -->
        {% include "base/js.html" %}
        

        {% block scripts %}
        {% endblock  %}

    </body>
</html>

mysite/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    
<div class="container" style="position: relative; display: inline-block; height:100%; width:100%" id="dashboard">
    <h1 class="title">Dashboard</h1>
    <div class="row">  

        <!-- first card -->
        <div class="column is-6">
            <div class="card card-link">
                
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <img :src="image">
                            <p class="title is-4"><a href="{% url 'events:user_participant_table' user.id %}">
                                Display Your Attended Events</a>
                            </p>
                        </div>
                    </div>

                    <div class="content">
                        
                    </div> 
                </div>

                <footer class="card-footer">
                    <a class="button is-dark card-footer-item" href="{% url 'events:create_event' %}">
                        Add New Event</a>&nbsp;&nbsp;
                    <a href="{% url 'events:table_event' user.id %}" class="card-footer-item button is-primary">
                            Display Your created Events</a>
                </footer>
                
            </div>
        </div> <br>

        <!-- second card -->
        <div class="column is-6">
            <div class="card card-link">
                
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <img :src="image">
                            <p class="title is-4"><a href="{% url 'events:table_participant' %}">
                                Display Attended Events Of All Users</a>
                            </p>
                        </div>
                    </div>

                    <div class="content">
                        
                    </div> 
                </div>

                <footer class="card-footer">
                    <a class="button is-dark card-footer-item" href="{% url 'events:create_event' %}">
                        Add New Event</a>&nbsp;&nbsp;
                    <!-- <a class="card-footer-item button is-danger" href="{% url 'events:user_expire_events' user.id %}">
                        Your Expire Event</a>&nbsp;&nbsp; -->
                    <a href="{% url 'list_active_events' %}" class="card-footer-item button is-primary">
                        Join Active Events</a>
                    <!-- <a href="{% url 'events:user_participant_table' user.id %}" class="card-footer-item">
                        Edit Participate In Users Events
                    </a> -->
                </footer>
                
            </div>
        </div> <br>

        <!-- third card  -->
        <div class="column is-6">
            <div class="card card-link">
                
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <img :src="image">
                            <p class="title is-4">
                                <a href="{% url 'events:withdraw_table' user.id %}">
                                Display Your Withdraw Events</a>
                            </p>
                        </div>
                    </div>

                    <div class="content">
                    </div> 
                </div>

                <footer class="card-footer">
                    <!-- <a class="button is-dark" href="{% url 'events:create_event' %}">
                        Add New Event
                    </a> &nbsp;&nbsp; -->
                    <a class="card-footer-item button is-info" href="{% url 'events:table_event' user.id %}">
                        Edit Your Events
                    </a>&nbsp;&nbsp;   
                    <a href="{% url 'list_expire_events' %}" class="card-footer-item button is-danger">
                        Display All Expire Events
                    </a>
                </footer>
                
            </div>
        </div> <br>

        <div class="column is-6">
            <div class="card card-link">
                
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <img :src="image">
                            <p class="title is-4"><a href="{% url 'events:table_deleted' user.id %}">
                                Display Your Deleted Events</a>
                            </p>
                        </div>
                    </div>

                    <div class="content">
                        
                    </div> 
                </div>

                <footer class="card-footer">
                    <!-- <a href="{% url 'events:table_event' user.id %}" class="card-footer-item button is-info">
                        Edit Events</a>&nbsp;&nbsp; -->
                    <a href="{% url 'events:table_deleted' user.id %}" class="card-footer-item button is-primary">
                        Reutrn Your Deleted Event</a> &nbsp;&nbsp;
                    <a class="card-footer-item button is-danger" href="{% url 'events:user_expire_events' user.id %}">
                        Your Expire Event</a>
                </footer>
                
            </div>
        </div> <br>

            

    </div>
</div>

{% endblock %}

{% block scripts %}
     <!-- scripts for VUE -->
     <script src="{% static 'vue/vue.js' %}"></script>
     <!-- <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->
     <script src="https://cdnjs.cloudfare.com/ajax/libs/axios/0.19.2/axios.min.js">
     </script>

        <script>
            
            var vue = new Vue ({
                el: '#dashboard',
                delimiters: ['[', ']'],
                data: {
                    image: "{% static 'img/2.png' %}",
                },
            });

        </script>


{% endblock %}

mysite/templates/frontpage.html
{% extends 'base.html' %}


{% block content %}
    
<section class="hero is-medium is-primary is-bold">
    
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Wellcome To Our Events Application</h1>
            
            {% if request.user.is_authenticated %}
                <h2 class="subtitle">We are happy to be with us {{user.username}} 
                    <a href="dashboard"> Goto Your Dashboard</a>
                </h2>
            {% else %}
                <h2 class="subtitle">We will be happy if you join us, Try to 
                    <a href="/accounts/signup/"><strong>Sign up</strong></a> now 
                </h2>
            {% endif %}                
        </div>
    </div>

</section>

{% endblock %}
    