mysite/events/urls.py
from django.urls import path
from events.views.events import create_event, edit_event, table_event
from events.views.participants import (add_participant, edit_participant, table_participant,
                                        user_participant_table, withdraw_table)
from events.views.deleted_events import delete_event, return_deleted, table_deleted 
from events.views.auto_join import join_specific_event, withdraw_specific_event
from events.views.search import search_event_date

from events.views.home import user_expire_events

app_name = 'events'
urlpatterns = [
    # for event add, edit 
    path('create/event/', create_event, name='create_event'),
    path('edit/event/<int:id>/', edit_event, name='edit_event'),

    # deleted and return deleted
    path('delete/event/<int:id>/', delete_event, name='delete_event'),
    path('return/deleted/event/<int:id>/', return_deleted, name='return_deleted'),
    path('all/deleted/event/for/user/<int:user>/', table_deleted, name='table_deleted'),

    # table create event for a user
    path('all/created/events/for/user/<int:user>/', table_event, name='table_event'),
    
    # for participants add, edit
    path('add/participant/', add_participant, name='add_participant'),
    path('edit/participant/<int:id>/', edit_participant, name='edit_participant'),
    
    # table participants  
    path('all/attended/events/for/all/users/', table_participant, name='table_participant'),
    path('all/attended/events/for/user/<int:user>/', user_participant_table, name="user_participant_table"),
    path('all/withdraw/events/for/user/<int:user>/', withdraw_table, name='withdraw_table'),
    
    # table expire for a user  
    path('all/expire/events/for/user/<int:user>/', user_expire_events, name='user_expire_events'),

    # join.py
    path('join/specific/event/<int:event_id>/<int:user>/', join_specific_event, name='join_specific_event'),
    path('withdraw/specific/event/<int:event_id>/<int:user>/', withdraw_specific_event, name='withdraw_specific_event'),

    # search.py
    path('search/date/from/to', search_event_date, name='search_event_date'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views

from events.views.home import frontpage, dashboard, list_active_events, list_expire_events
# from accounts.views import signup, register_page, login_page

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # for home.py
    path('', frontpage, name='frontpage'),
    path('dashboard/', dashboard, name='dashboard'),
    path('list/all/active/events/', list_active_events, name='list_active_events'),
    path('list/all/expire/events/', list_expire_events, name='list_expire_events'),
    
    # events App.
    path('events/', include('events.urls', namespace='events')),
    
    # authentication App.
    path('accounts/', include('allauth.urls')),
    
    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

    # path('signup/', register_page, name='signup'),
    # path('login/', login_page, name='login'),
    
    # path('login/', views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

mysite/templates/base/css.html
{% load static %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
       
<!-- <link rel="icon" type="image/png" href="{% static 'favicon/favicon.ico' %}"> -->

<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">

<link rel="icon" type="image/png" href="{% static 'favicon/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<!-- <link rel="stylesheet" href="{% static 'css/bootstrap413.min.css' %}"> -->
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
<!-- <link rel="stylesheet" href="{% static 'styles/main.css' %}" -->

mysite/templates/base/js.html
{% load static %}


 <!-- scripts for VUE -->
 <script src="{% static 'vue/vue.js' %}"></script>
 <!-- <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->
 <!-- <script src="https://cdnjs.cloudfare.com/ajax/libs/axios/0.19.2/axios.min.js"> -->
 </script>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
 <script src="{% static 'js/popper.min.js' %}"></script>
 <script src="{% static 'js/bootstrap413.min.js' %}"></script>
 <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->

 <script>

     var vue = new Vue ({
         el: '#footer-vue',
         delimiters: ['[', ']'],
         data: {
             msg: ' coded by Amr Aly',
             image: "{% static 'img/2.png' %}",
         },
     });

 </script>

mysite/templates/base/messages.html
 <section class="section">
            
    {% if messages %}
        {% for message in messages %}
            <article class="message is-{{ message.tags }}">
                <div class="message-body">
                    {{ message }}
                </div>
            </article>
        
        {% endfor %}
    {% endif %}
    <br>
    
</section>

mysite/templates/base/navbar.html
<!-- <nav class="navbar navbar-expand-lg has-background-primary-light has-navbar-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/"><strong>Events Application</strong></a>
    </div> -->

<!-- <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="/">Events</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button> 
   
    
    <div class="navbar-menu" id="navbarCollapse">
        {% if request.user.is_authenticated %}
            <div class="navbar-start">
                <a href="/dashboard" class="navbar-item">Dashboard</a>
                <a href="{% url 'events:create_event' %}" class="navbar-item">Create New Events</a>
                <a href="{% url 'list_active_events' %}" class="navbar-item">Active Events</a>
                <a href="{% url 'list_expire_events' %}" class="navbar-item">Expire Events</a>
                <a href="{% url 'events:table_event' user.id %}" class="navbar-item">Your Created Events</a>
            </div>
        {% endif %}
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    {% if request.user.is_authenticated %}
                        <p><strong>Wellcome : {{ user.username }}</strong></p> &nbsp;&nbsp;&nbsp;
                        <a href="{% url 'account_logout' %}" class="button is-danger">Log out</a>
                    {% else %}
                        <a href="{% url 'account_signup' %}" class="button is-primary">
                            <strong>Sign up</strong></a>
                        <a href="{% url 'account_login' %}" class="button is-dark">Log in</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav> -->

<!--  -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="/">Events </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/dashboard">Dashboard </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'events:create_event' %}" class="navbar-item">Create New Events</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'list_active_events' %}" class="navbar-item">Active Events</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'list_expire_events' %}" class="navbar-item">Expire Events</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'events:table_event' user.id %}" class="navbar-item">Your Created Events</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Wellcome: {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="#{% url 'account_change_password' %}">Change password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link btn btn-danger" href="{% url 'account_logout' %}" class="navbar-item">
                        Logout</a>
                </li>
            </ul>
        {% else %}
            <form class="form-inline ml-auto">
            <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
        {% endif %}
    </div>
  </nav>

mysite/templates/base/search_bar.html
<!-- div for searh events date -->
<div class="align-content-center" style="background-color:transparent; height: 100%; width: 100%; margin: 30px;
padding: 10px; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px darkgray;" id="search-div" name="mydiv">
    <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'events:search_event_date' %}">
        <input class="form-control mr-sm-2" type="text" name='from' placeholder="Search Event Date from ..." value="{{request.GET.from}}" aria-label="Search">
        <input class="form-control mr-sm-2" type="text" name='to' placeholder="Search Event Date to ..." value="{{request.GET.to}}" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    </form>
</div>