mysite/events/urls.py
from django.urls import path
from events.views.events import create_event, edit_event, table_event
from events.views.participants import (add_participant, edit_participant, table_participant,
                                        user_participant_table, withdraw_table)
from events.views.deleted_events import delete_event, return_deleted, table_deleted 
from events.views.auto_join import join_specific_event, withdraw_specific_event
from events.views.search import search_event_date

from events.views.home import user_expire_events

app_name = 'events'
urlpatterns = [
    # for event add, edit 
    path('create/event/', create_event, name='create_event'),
    path('edit/event/<int:id>/', edit_event, name='edit_event'),

    # deleted and return deleted
    path('delete/event/<int:id>/', delete_event, name='delete_event'),
    path('return/deleted/event/<int:id>/', return_deleted, name='return_deleted'),
    path('all/deleted/event/for/user/<int:user>/', table_deleted, name='table_deleted'),

    # table create event for a user
    path('all/created/events/for/user/<int:user>/', table_event, name='table_event'),
    
    # for participants add, edit
    path('add/participant/', add_participant, name='add_participant'),
    path('edit/participant/<int:id>/', edit_participant, name='edit_participant'),
    
    # table participants  
    path('all/attended/events/for/all/users/', table_participant, name='table_participant'),
    path('all/attended/events/for/user/<int:user>/', user_participant_table, name="user_participant_table"),
    path('all/withdraw/events/for/user/<int:user>/', withdraw_table, name='withdraw_table'),
    
    # table expire for a user  
    path('all/expire/events/for/user/<int:user>/', user_expire_events, name='user_expire_events'),

    # join.py
    path('join/specific/event/<int:event_id>/<int:user>/', join_specific_event, name='join_specific_event'),
    path('withdraw/specific/event/<int:event_id>/<int:user>/', withdraw_specific_event, name='withdraw_specific_event'),

    # search.py
    path('search/date/from/to', search_event_date, name='search_event_date'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views

from events.views.home import frontpage, dashboard, list_active_events, list_expire_events
# from accounts.views import signup, register_page, login_page

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # for home.py
    path('', frontpage, name='frontpage'),
    path('dashboard/', dashboard, name='dashboard'),
    path('list/all/active/events/', list_active_events, name='list_active_events'),
    path('list/all/expire/events/', list_expire_events, name='list_expire_events'),
    
    # events App.
    path('events/', include('events.urls', namespace='events')),
    
    # authentication App.
    path('accounts/', include('allauth.urls')),
    
    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

    # path('signup/', register_page, name='signup'),
    # path('login/', login_page, name='login'),
    
    # path('login/', views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

mysite/events/views/home.py
from events.tables.tables import ParticipantTable
from django.shortcuts import render
from ..models import Event, Participant
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from datetime import datetime, date
# from time import timezone
from django.contrib.auth.decorators import login_required


def frontpage(request):
    ''' This method to handel frontpage '''
    return render(request, 'frontpage.html', {})


@login_required
def dashboard(request): 
    ''' Handling dashboard page '''
    return render(request, 'dashboard.html', {})


@login_required
def list_active_events(request):
    ''' Handling display of all events of any user that have created '''
    ################################################  Important Hint   #############################################################################
    
    ################################################################################################################################################
    user_id = request.user.id
    event_time = date.today()  # or you can use ==>>  datetime.now()

    ## .active() means not deleted take a look at models.py
    event = Event.objects.filter(eventdate__gte=event_time).active().order_by('-eventdate') 

    count = Participant.objects.values('event') \
                                .annotate(ncount=Count('user'))\
                                .filter(attended=True)  # to get participants count 

    ## for give a hint to user if he attended the event or not 
    user_attend = Participant.objects.values('event', 'attended').filter(user=user_id)  
    # print()

    ## next lines for paginate all active events
    paginator = Paginator(event, 4) 
    page = request.GET.get('page')
    try:
        event_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        event_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        event_page = paginator.page(paginator.num_pages)
    
    context = {
        'user_attend': user_attend,
        'event_page': event_page,
        'page': page,
        'count': count,
    }
    return render(request, 'home/list_active_events.html', context)


@login_required
def list_expire_events(request):
    ''' Handeling expire events for all users '''
    today = date.today()
    expire_events = Event.objects.filter(eventdate__lt=today).order_by('-eventdate')
    
    paginator = Paginator(expire_events, 4) 
    page = request.GET.get('page')

    try:
        event_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        event_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        event_page = paginator.page(paginator.num_pages)

    count = Participant.objects.values('event') \
                                .annotate(ncount=Count('user'))\
                                .filter(attended=True)  # to get participants count 
    
    context= {
        'event_page': event_page,
        'page': page,
        'count': count,
    }
    return render(request, 'home/list_expire_events.html', context)


@login_required
def user_expire_events(request, user):
    ''' All expire events of specific user '''

    # get all expire events ID of a specific user 
    qs = Participant.objects.select_related('event') \
                            .filter(event__eventdate__lt=date.today(), user=user) \
                            .order_by('-events_event.eventdate')
    
    # to make pagination input in templates 
    page_no = request.GET.get('pageno')
    if page_no == None or page_no == '' or int(page_no) == 0:
        table = ParticipantTable(qs, exclude='user, join, withdraw')
        table.paginate(page=request.GET.get('page', 1), per_page=10)
    else:
        table = ParticipantTable(qs, exclude='user, join, withdraw')
        table.paginate(page=request.GET.get('page', 1), per_page=page_no)

    context = {
        'user_expire_events_table': table,
    }
    return render(request, 'events/tables/user_expire_events.html', context)

mysite/templates/home/list_active_events.html
{% extends 'base.html' %}
{% load static %}
{% load render_table from django_tables2 %}
{% block content %}
    
    <div class="container" style="position: relative; display: inline-block; height:100%; width:100%">
        <h1 class="title">All Available Events Of All Users</h1>
        <div class="row">  
        
            {% for obj in event_page %}
              
                <div class="column is-6">
                    <div class="card card-link">
                        
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content">
                                    
                                </div>
                            </div>

                            <div class="content">
                                <p class="title is-4">Event ID: {{ obj.id }}</p>
                                <p class="title is-4">Event Owner: {{ obj.user.username }}</p>
                                <p class="title is-4">Event Title : {{ obj.title }}</p>
                                <p class="title is-4">Event Date : {{ obj.eventdate }}</p>
                                <p class="title is-4">Participants : 
                                    {% for c in count %}
                                        {% if c.event == obj.id %}   
                                            {{ c.ncount }} <br>
                                        {% endif %}
                                    {% endfor %}
                                </p>
                                <!-- This loop for give a hint to user if he attended the event or not -->
                                {% for i in user_attend %}
                                    {% if i.event == obj.id %}
                                        {% if i.attended %}   
                                            <p style="background-color: lightgreen;width: 10%;">
                                                <small> Joined</small>
                                            </p>&nbsp;&nbsp;
                                        {% elif not i.attended %}
                                            <p style="background-color: lightpink;width: 15%;">
                                                <small> Withdrawed</small>
                                            </p>&nbsp;&nbsp;
                                        {% else %}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}  
                                    
                            </div> 
                        </div>

                        <footer class="card-footer">
                            <a class="button is-dark" href="{% url 'events:create_event' %}" class="card-footer-item">
                                Create New Event
                            </a>&nbsp;&nbsp;
                            {% if obj.user.id == request.user.id  %}
                                
                                <a class="button is-info" href="{% url 'events:edit_event' obj.id %}">
                                    Edit Event</a>&nbsp;&nbsp;
                                <!-- <a class="button is-danger" href="{% url 'events:withdraw_specific_event' obj.id user.id %}">
                                    Withdraw</a> &nbsp;&nbsp; -->
                            {% else %}
                            {% endif %}
                            
                            <a class="button is-primary" href="{% url 'events:join_specific_event' obj.id user.id %}">
                                Join 
                            </a>&nbsp;&nbsp; 
                            <a class="button is-danger" href="{% url 'events:withdraw_specific_event' obj.id user.id %}" >
                                Withdraw
                            </a> &nbsp;&nbsp;
                                
                        </footer>
                        
                    </div>
                </div> <br>
                {% endfor %}

        </div>
    </div>
    

{% endblock %}

mysite/templates/home/list_all_events.html
{% extends 'base.html' %}
{% load static %}
{% load render_table from django_tables2 %}
{% block content %}
    
    <div class="container" style="position: relative; display: inline-block; height:100%; width:100%">
        <h1 class="title">Dashboard</h1>
        <div class="row">  
            {% for obj in event_page %}
              
                <div class="column is-6">
                    <div class="card card-link">
                        
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content">
                                    
                                </div>
                            </div>

                            <div class="content">
                                <p class="title is-4">Event ID: {{ obj.id }}</p>
                                <p class="title is-4">Event Owner: {{ obj.user.username }}</p>
                                <p class="title is-4">Event Title : {{ obj.title }}</p>
                                <p class="title is-4">Event Date : {{ obj.eventdate }}</p>
                                <p class="title is-4">Event Participants : 
                                    {% for c in count %}
                                        {% if c.event == obj.id %}   
                                            {{ c.ncount }}
                                        {% endif %}
                                    {% endfor %}
                                </p>
                            </div> 
                        </div>

                        <footer class="card-footer">
                            <a class="button is-dark" href="{% url 'events:create_event' %}" class="card-footer-item">Add New Event</a>
                            &nbsp;&nbsp;
                            {% if obj.user.id == request.user.id  %}
                                <a class="button is-info" href="{% url 'events:edit_event' obj.id %}" class="card-footer-item">Edit Event</a>&nbsp;&nbsp;
                            {% else %}
                                <!-- <a href="{% url 'events:table_event' user.id %}" class="card-footer-item">All Your Events</a> -->
                            {% endif %}
                            <!-- <a href="{% url 'events:add_participant' %}" class="card-footer-item">Join An Events</a> -->
                            <a class="button is-danger" href="{% url 'events:withdraw_specific_event' obj.id user.id %}" class="card-footer-item">Withdraw</a> &nbsp;&nbsp;
                            <a class="button is-primary" href="{% url 'events:join_specific_event' obj.id user.id %}" class="card-footer-item">Join</a>
                            
                                
                        </footer>
                        
                    </div>
                </div> <br>
                {% endfor %}

        </div>
    </div>
    

{% endblock %}

mysite/templates/home/list_expire_events.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    
    <div class="container" style="position: relative; display: inline-block; height:100%; width:100%">
        <h1 class="title">All Expire Events Of All Users</h1>
        <div class="row">  
        
            {% for obj in event_page %}
              
                <div class="column is-6">
                    <div class="card card-link">
                        
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content">
                                    
                                </div>
                            </div>

                            <div class="content">
                                <p class="title is-4">Event ID: {{ obj.id }}</p>
                                <p class="title is-4">Event Owner: {{ obj.user.username }}</p>
                                <p class="title is-4">Event Title : {{ obj.title }}</p>
                                <p class="title is-4">Event Date : {{ obj.eventdate }}</p>
                                <p class="title is-4">Event Participants : 
                                    {% for c in count %}
                                        {% if c.event == obj.id %}   
                                            {{ c.ncount }}
                                        {% endif %}
                                    {% endfor %}
                                </p>
                            </div> 
                        </div>

                        <footer class="card-footer">
                            <a class="card-footer-item button is-dark" href="{% url 'events:create_event' %}">Add New Event</a>
                            &nbsp;&nbsp;
                            {% if obj.user.id == request.user.id  %}
                                <a class="button is-info" href="{% url 'events:edit_event' obj.id %}">
                                    Edit Event</a>&nbsp;&nbsp;
                            {% else %}
                            {% endif %}
                                
                        </footer>
                        
                    </div>
                </div> <br>
                {% endfor %}

        </div>
    </div>
    

{% endblock %}

mysite/templates/home/pagination.html
<!-- <div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="{{ page.previous_page_number }}" class="btn btn-primary" role="button" id="btn-edit-id">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}" class="btn btn-primary" role="button" id="btn-edit-id">Next</a>
    {% endif %}
  </span>
</div> -->

<!--  -->
<section class="section">

  <div class="pagination center">
    <span class="step-links">
        <!-- {% if cl_data.has_previous %}
            <a href="?page={{ cl_data.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span> {% if cl_data.has_next %}
    <a href="?page={{ cl_data.next_page_number }}">Next</a> {% endif %} -->
    {% if event_page %}
      {% if page.has_other_pages %}
        <ul class="pagination">
          {% if page.has_previous %}
            <li><a class="button is-primary" href="?page={{ page.previous_page_number }}" id="laquo-prev"> &laquo; previous</a></li>
              <!-- <input type="button" onclick="window.location.href='?page={{ page.previous_page_number }}';" id="laquo-prev" value="&laquo;" /> -->
          {% else %}
            <!-- <input type="button" class="disabled" value="&laquo;" /> -->
            <li class="button is-primary disabled"><span>&laquo;</span></li>
          {% endif %}
          {% for i in page.paginator.page_range %}
            {% if page.number == i %}
              <!-- <input type="button" class="active" value="{{ i }}" /> -->
              <li class="button is-dark active"> <span>{{ i }} <span class="sr-only" id="current-num">(current)</span></li>
            {% else %}
            <!-- <a type="button" href="?page={{ i }}">{{ i }}</a> -->
              <!-- <input type="button" onclick="window.location.href='?page={{ i }}';" value="{{ i }}" /> -->
              <li><a class="button is-primary" type="button" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page.has_next %}
            <!-- <input type="button" onclick="window.location.href='?page={{ page.next_page_number }}';" value="&raquo;" /> -->
            <li> <a class="button is-primary" type="button" href="?page={{ page.next_page_number }}">next &raquo; </a></li>
          {% else %}
            <!-- <input type="button" class="disabled" value="&raquo;" /> -->
            <li class="button is-primary disabled"><span>&raquo;</span></li>
          {% endif %}
        </ul>
      {% endif %}

    {% else %}

      {% if page.has_other_pages %}
        <ul class="pagination">
          {% if page.has_previous %}
              <!-- <input type="button" href="?page={{ page.previous_page_number }}" value="&laquo;" /> -->
            <li> <a type="button" href="?page={{ page.previous_page_number }}">&laquo;</a></li>
          {% else %}
            <!-- <input type="button" class="disabled" value="&laquo;"/> -->
            <li class="disabled"><span>&laquo;</span></li>
          {% endif %}

          {% for i in page.paginator.page_range %}
              {% if page.number == i %}
                <!-- <input type="button" class="active" value="{{ i }}" /> -->
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></li>
              {% else %}
                  <!-- <input type="button" href="?page={{ i }}" value="{{ i }}" /> -->
                <li> <a type="button" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %} 
          {% endfor %}

          {% if page.has_next %}
              <!-- <input type="button" href="?page={{ page.next_page_number }}" value="&raquo;" /> -->
            <li> <a type="button" href="?page={{ page.next_page_number }}">&raquo;</a></li>
          {% else %}
              <!-- <input type="button" class="disabled" value="&raquo;" /> -->
            <li class="disabled"><span>&raquo;</span></li>
          {% endif %}
        </ul>
        {% endif %}
    {% endif %}
        </span>
  </div>

</section>